import { Product } from "@/features/product/product.types";

export const productSeedData: Product[] = [
    {
        uid: "1",
        name: "Wireless Mouse",
        short_description: "Ergonomic wireless mouse",
        description: "A comfortable ergonomic wireless mouse with adjustable DPI and long battery life.",
        sku: "WM-001",
        price: "25.99",
        category_uid: "cat-1",
    },
    {
        uid: "2",
        name: "Mechanical Keyboard",
        short_description: "RGB mechanical keyboard",
        description: "High-quality mechanical keyboard with customizable RGB lighting and blue switches.",
        sku: "MK-002",
        price: "79.99",
        category_uid: "cat-1",
    },
    {
        uid: "3",
        name: "Gaming Headset",
        short_description: "Surround sound headset",
        description: "Gaming headset with 7.1 surround sound and noise-canceling microphone.",
        sku: "GH-003",
        price: "59.99",
        category_uid: "cat-2",
    },
    {
        uid: "4",
        name: "USB-C Hub",
        short_description: "Multiport adapter",
        description: "USB-C hub with HDMI, USB 3.0, and SD card slots.",
        sku: "UH-004",
        price: "39.99",
        category_uid: "cat-3",
    },
    {
        uid: "5",
        name: "4K Monitor",
        short_description: "Ultra HD display",
        description: "27-inch 4K UHD monitor with vibrant colors.",
        sku: "MON-005",
        price: "299.99",
        category_uid: "cat-4",
    },
    {
        uid: "6",
        name: "Laptop Stand",
        short_description: "Adjustable stand",
        description: "Aluminum adjustable laptop stand for better ergonomics.",
        sku: "LS-006",
        price: "19.99",
        category_uid: "cat-3",
    },
    {
        uid: "7",
        name: "External Hard Drive",
        short_description: "1TB portable drive",
        description: "Portable external hard drive with fast USB 3.0 support.",
        sku: "HD-007",
        price: "64.99",
        category_uid: "cat-5",
    },
    {
        uid: "8",
        name: "Webcam",
        short_description: "HD webcam",
        description: "1080p HD webcam with built-in microphone.",
        sku: "WC-008",
        price: "49.99",
        category_uid: "cat-2",
    },
    {
        uid: "9",
        name: "Bluetooth Speaker",
        short_description: "Portable speaker",
        description: "Compact Bluetooth speaker with deep bass.",
        sku: "BS-009",
        price: "34.99",
        category_uid: "cat-2",
    },
    {
        uid: "10",
        name: "Smartphone Stand",
        short_description: "Desk phone holder",
        description: "Adjustable smartphone stand for desks.",
        sku: "SS-010",
        price: "9.99",
        category_uid: "cat-3",
    },
    {
        uid: "11",
        name: "Wireless Charger",
        short_description: "Fast charging pad",
        description: "Qi-certified wireless charging pad.",
        sku: "WC-011",
        price: "22.99",
        category_uid: "cat-3",
    },
    {
        uid: "12",
        name: "Gaming Mouse Pad",
        short_description: "Large mouse pad",
        description: "Extended gaming mouse pad with smooth surface.",
        sku: "MP-012",
        price: "14.99",
        category_uid: "cat-1",
    },
    {
        uid: "13",
        name: "Noise Cancelling Earbuds",
        short_description: "Wireless earbuds",
        description: "True wireless earbuds with active noise cancellation.",
        sku: "EB-013",
        price: "89.99",
        category_uid: "cat-2",
    },
    {
        uid: "14",
        name: "Desk Lamp",
        short_description: "LED desk lamp",
        description: "Adjustable LED desk lamp with touch controls.",
        sku: "DL-014",
        price: "27.99",
        category_uid: "cat-6",
    },
    {
        uid: "15",
        name: "Power Bank",
        short_description: "10000mAh battery",
        description: "Portable power bank with fast charging.",
        sku: "PB-015",
        price: "29.99",
        category_uid: "cat-3",
    },
    {
        uid: "16",
        name: "Ethernet Cable",
        short_description: "Cat6 cable",
        description: "High-speed Cat6 Ethernet cable for stable internet.",
        sku: "EC-016",
        price: "7.99",
        category_uid: "cat-5",
    },
    {
        uid: "17",
        name: "Graphics Tablet",
        short_description: "Drawing tablet",
        description: "Digital drawing tablet for designers.",
        sku: "GT-017",
        price: "119.99",
        category_uid: "cat-7",
    },
    {
        uid: "18",
        name: "VR Headset",
        short_description: "Virtual reality headset",
        description: "Immersive VR headset for gaming and experiences.",
        sku: "VR-018",
        price: "399.99",
        category_uid: "cat-7",
    },
    {
        uid: "19",
        name: "Smartwatch",
        short_description: "Fitness smartwatch",
        description: "Smartwatch with heart rate tracking and notifications.",
        sku: "SW-019",
        price: "149.99",
        category_uid: "cat-8",
    },
    {
        uid: "20",
        name: "Portable Projector",
        short_description: "Mini projector",
        description: "Compact projector for movies and presentations.",
        sku: "PJ-020",
        price: "199.99",
        category_uid: "cat-4",
    },
    {
        uid: "21",
        name: "USB Flash Drive",
        short_description: "64GB USB drive",
        description: "Compact USB 3.0 flash drive with 64GB storage.",
        sku: "FD-021",
        price: "12.99",
        category_uid: "cat-5",
    },
];
