"""updated the relationship

Revision ID: baf6b010b146
Revises: c02cf7493093
Create Date: 2026-04-03 12:32:53.733230

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "baf6b010b146"
down_revision: Union[str, Sequence[str], None] = "c02cf7493093"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
