"""updated the category

Revision ID: c02cf7493093
Revises: 641eeca263cf
Create Date: 2026-04-03 11:55:26.181150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c02cf7493093"
down_revision: Union[str, Sequence[str], None] = "641eeca263cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False
    )
    op.create_foreign_key(
        None, "categories", "categories", ["parent_id"], ["uid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###
